[package]
name = "metrowaii/rodux-hooks"
description = "Roact hooks for Rodux"
authors = ["SolarHorizon"]
version = "0.3.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
Roact = "core-packages/roact-compat@17.0.1-rc.16.1"
